[adapters.binance_spot]
type = "binance_spot_ws"
symbols = [
  "ASTER",
  "ZEC",
  "NEAR",
  "FIL",
  "XPL",
  "AAVE",
  "USELESS",
  "SOL",
  "PUMP",
  "LINEA",
  "EIGEN",
  "ONDO",
  "LINK",
  "OP",
  "LTC",
  "PEPE",
  "FLOKI",
  "DOGE",
  "SHIB",
  "AVAX",
  "BNB",
  "BTC",
  "ETH",
]

[adapters.binance_perp]
type = "binance_perp_ws"
symbols = [
  "ASTER",
  "ZEC",
  "NEAR",
  "FIL",
  "XPL",
  "AAVE",
  "USELESS",
  "SOL",
  "PUMP",
  "LINEA",
  "EIGEN",
  "ONDO",
  "LINK",
  "OP",
  "LTC",
  "PEPE",
  "FLOKI",
  "DOGE",
  "SHIB",
  "AVAX",
  "BNB",
  "BTC",
  "ETH",
  
]

[runtime]
tbt_window_multiplier = 4.0
tanh_k = 0.10
scale_window_seconds = 600.0
